### ISSUE TITLE
Time to send messages & receive in vehicle adapter

### ISSUE THREAD

**Issue by bjornborg** [alexvoronov/geonetworking#13] opened 2016-03-07 13:22 UTC
Hello, for the past few days I've been testing the vehicle adapter along with the link layer (udp2eth).

So far nothing wrong for the link layer for sending and receiving data.

However, it seems there are some problems with the vehicle adapter for sending messages sometimes as it does not consistently output the messages on a 25 Hz frequency. Sometimes it even takes several seconds (1-8 seconds) to send a message. I measured the time as taken from the timestamp right before receiving a packet from simulink to right after sending the packet to the link layer. 

Furthermore, additional tests gave indication that message congestion might be a problem for the vehicle adapter, as the packets started to "pile up" when it received packages from several distinct sources (cam, denm and iclcm messages) at 25 Hz but I have not investigated this further.

I will post figures containing the time distribution of the vehicle adapter shortly.

**Comment by Zeverin** [comment] 2016-03-07 13:28
That's indeed a big problem. Could you please tell me some more about the setup you're running? JRE version, hardware, operating system?

**Comment by bjornborg** [comment] 2016-03-07 14:28
The hardware should be the one from http://www.pcengines.ch/apu.htm along with wifi card Atheros Ar9280. The system is running Arch linux along with the default JRE version provided by jdk8-openjdk.




![va_send1](https://cloud.githubusercontent.com/assets/9810017/13571972/27002704-e478-11e5-94a7-3d0fff25c297.jpg)
![va_receive](https://cloud.githubusercontent.com/assets/9810017/13571971/26ff8650-e478-11e5-8ca5-c7bf40b39e2e.jpg)
![ll_send](https://cloud.githubusercontent.com/assets/9810017/13571973/27003bd6-e478-11e5-8d87-1d1cda6ae2dd.jpg)
![ll_receive](https://cloud.githubusercontent.com/assets/9810017/13571974/270045ae-e478-11e5-86cf-358c5ce8311b.jpg)

**Comment by Zeverin** [comment] 2016-03-07 16:54
Thanks
Could you please try rerunning the tests with the output piped to /dev/null? It will help isolate the problem if the bottle neck is the time spent writing the terminal output to the screen/disk. You could do it like this:
./run.sh > /dev/null

**Comment by bjornborg** [comment] 2016-03-09 13:55
It seems the bottle neck was the all the writing to the terminal and solves the problem.
![receive](https://cloud.githubusercontent.com/assets/9810017/13637193/505e724c-e606-11e5-906d-defc0f78fe19.jpg)
![send](https://cloud.githubusercontent.com/assets/9810017/13637194/505f9e92-e606-11e5-91d9-99c4893f6e5d.jpg)

As it stands currently, it solves the major problem. However a minor problem still exists, IF there were a great number of vehicles within our range, all broadcasting the packets will queue up which could be a problem in the future. But I guess this is something we won't consider?

**Comment by Zeverin** [comment] 2016-03-09 14:20
I'm glad to hear that it works. Optimizing the printouts would still be a good idea, as it would be nice to allow for error and warning printouts with reasonable performance.

For the other problem. How many vehicles are we talking about here? If you find some more info on what the problem is and what the potential bottle necks might be I could help with implementing a fix. For example if you do some performance profiling and figure out what's taking the most time I could probably optimize that.

**Comment by bjornborg** [comment] 2016-03-09 14:26
I mean, there is still a possibility if a congestion (far more than 11 vehicles obviously) would occur, there might be a packet overflow due to some unforeseen bottlenecks (most unlikely but possible). I am just stating that it might be a irrelevant problem today, but in the future it could be a problem and how that should be solved.

**Comment by jandejongh** [comment] 2016-03-09 14:33
Hi Bjorn, Thanks for the data and for the tests.

I share your concern. @25 Hz (not adaptive to velocity, etc.), we should expect channel congestion to occur with (I estimate) 12 vehicles, if not sooner.

Back-of-the-envelope (and a bit on the pessimistic side):

- We have only 6 Mbps 'raw' in the channel;
- We can reasonably use it up to 50% utilization (3 Mbps) before excessive collisions and packet losses occur;
- Contention for and transmission of a message (say 3,000 bits) could take one to several milliseconds, depending on the 802.11 parameters.

-> at most a few hundred messages per second in total
-> at most a dozen vehicles...

Within ETSI, the (DCC) approach is to adaptively set the CAM transmission rate for vehicles, depending on vehicle state (velocity, ...) and 'channel state'. If the channel utilization becomes too high, the maximum CAM rate is lowered.

In I-Game/GCDC we do not follow DCC (as far as I know, it has not been fully ratified either), but instead give all possible room to the platooning/CACC use cases. This decision was not taken lightly...

A bit opinionated, but I think a future deployment of such  '25 Hz systems' will certainly need more 'spectrum', e.g., in the 60 GHz band.

BR,
Jan

**Comment by Zeverin** [comment] 2016-03-09 17:31
I think the proper ETSI spec. limits you to send CAM at 10Hz. Worth remembering is that ITS-G5 isn't meant for vehicle automation, which is my we're not complying with the spec. for GCDC and why we have iCLCM.
The solution to avoiding congestion in the vehicle adapter could be to start dropping packets when there's too much traffic, but I doubt that I'll work on that before the competition. If it's too slow we could just run the vehicle adapter on a bigger computer. So unless someone wants to do some further performance testing or profiling we should close the issue :)

**Comment by jandejongh** [comment] 2016-03-09 19:21
Hi Zeverin, actually the CAM rate as in Draft now is between 2 and 10 Hz, and governed by so-called CAM-triggers (change of position; change of velocity; change of heading), and also under control of the (measured/estimated) ITS-G5 channel load (the infamous T_gen_CAM_DCC parameter...). But maybe things have changed again in this respect :-).

For the competition, I guess we should just be careful not to have too many vehicles operational at the same time (we are thinking of evading to another channel for everyone that is 'just testing').

However, you are quite right that this discussion has little to do with Alex's geonetworking/VehicleAdapter implementation, so I concur with closing this issue, and perhaps pick it up on the I-Game forum. I just wanted to make clear that in I-Game, we do not neglect the issue of channel congestion in the face of 25Hz update rates (and no DCC implementation).

BR, Jan

**Comment by Zeverin** [comment] 2016-03-09 19:36
I agree. We'll especially have a problem with 25Hz CAM + 25Hz iCLCM + 10Hz DENM, giving us up to 60 messages per vehicle per second. Do you think we can do that reliably?

**Closed** 2016-03-13 14:55 UTC
